package com.yb.hi.entity.emr;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * 病历质控缺陷项(病历P5a): 质控规则命中即落一条缺陷, defect_type 六分类(时效/完整/逻辑/规范/内涵/首页),
 * severity 分级控制(1提醒/2拦截/3禁止), status 走 未整改→已整改/已申诉→申诉驳回/豁免 整改闭环;
 * auto_generated 区分人工登记(0)与自动检出(1)。表由 DictSchemaMigration 启动期幂等建出。
 * 说明: tenant_id 由 MyBatis-Plus 租户插件自动注入/过滤, 实体不显式映射, 避免插入重复列。
 */
@Data
@TableName("his_emr_qc_defect")
public class HisEmrQcDefect implements Serializable {

    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /** 病历记录ID(his_inp_medical_record.id) */
    private Long recordId;
    /** 就诊ID(住院his_inp_visit.id/门诊his_visit.id) */
    private Long visitId;
    /** 患者ID */
    private Long patientId;
    /** 质控规则ID(his_emr_quality_rule.id) */
    private Long ruleId;
    /** 规则编码(冗余, 便于追溯) */
    private String ruleCode;
    /** 规则名称(冗余, 便于展示) */
    private String ruleName;
    /** 缺陷类型: 时效/完整/逻辑/规范/内涵/首页 */
    private String defectType;
    /** 缺陷描述 */
    private String defectDesc;
    /** 扣分分值 */
    private BigDecimal deductScore;
    /** 严重程度: 1提醒 2拦截 3禁止 */
    private Integer severity;
    /** 质控环节: 1运行 2归档 */
    private Integer qcStage;
    /** 来源: 0人工 1自动 */
    private Integer autoGenerated;
    /** 状态: 0未整改 1已整改 2已申诉 3申诉驳回 4豁免 */
    private Integer status;
    /** 整改时间 */
    private LocalDateTime rectifyTime;
    /** 整改说明 */
    private String rectifyNote;
    /** 创建人 */
    @TableField(fill = FieldFill.INSERT)
    private String createBy;
    /** 创建时间 */
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createTime;
    /** 更新人 */
    @TableField(fill = FieldFill.UPDATE)
    private String updateBy;
    /** 更新时间 */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updateTime;
    /** 逻辑删除: 0正常 1删除 */
    @TableLogic
    private Integer deleted;
}

