package com.yb.hi.entity.inpatient;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.yb.hi.framework.entity.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.time.LocalDateTime;

/**
 * 护理临床事件(P4c): 入科/出科/死亡/手术/转入/转出/分娩/抢救事件时间轴, auto_generated 区分手动登记与自动触发(医嘱/就诊状态)
 */
@Data
@EqualsAndHashCode(callSuper = true)
@TableName("his_nursing_clinical_event")
public class HisNursingClinicalEvent extends BaseEntity {

    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /** 机构ID */
    private Long orgId;
    /** 住院就诊ID(his_inp_visit.id) */
    private Long inpVisitId;
    /** 患者ID(his_patient.id) */
    private Long patientId;
    /** 事件类型:admission/discharge/death/surgery/transfer_in/transfer_out/delivery/resuscitation */
    private String eventType;
    /** 事件时间 */
    private LocalDateTime eventTime;
    /** 事件描述 */
    private String eventDesc;
    /** 0手动 1自动生成 */
    private Integer autoGenerated;
    /** 触发源类型:order/visit_status/manual */
    private String sourceType;
    /** 触发源ID */
    private Long sourceId;
}
