-- 全系统数量/单价/金额精度统一: 价16,6 量16,4 额16,2 (2026-10-03 二期, 含药房/药库/采购/调拨内部口径)
-- 幂等可重放; 逐列经 information_schema 实查保留原可空性/默认值/注释
ALTER TABLE his_case_front_page
  MODIFY COLUMN bed_cost DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '搴婁綅璐?',
  MODIFY COLUMN drug_cost DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鑽搧璐?',
  MODIFY COLUMN exam_cost DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '妫€鏌ヨ垂',
  MODIFY COLUMN insurance_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍖讳繚鏀粯閲戦',
  MODIFY COLUMN material_cost DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鏉愭枡璐?',
  MODIFY COLUMN nursing_cost DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎶ょ悊璐?',
  MODIFY COLUMN other_cost DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍏朵粬璐圭敤',
  MODIFY COLUMN self_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鑷粯閲戦',
  MODIFY COLUMN total_cost DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎬昏垂鐢?',
  MODIFY COLUMN treatment_cost DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '娌荤枟璐?';
ALTER TABLE his_charge_bill
  MODIFY COLUMN acct_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '涓处鏀粯',
  MODIFY COLUMN cash_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鐜伴噾鏀粯',
  MODIFY COLUMN fund_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍩洪噾鏀粯',
  MODIFY COLUMN self_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鑷粯閲戦';
ALTER TABLE his_daily_settle
  MODIFY COLUMN acct_total DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '涓处鍚堣',
  MODIFY COLUMN alipay_total DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鏀粯瀹濆悎璁?鏀惰垂-閫€璐瑰噣棰?',
  MODIFY COLUMN card_total DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '閾惰鍗″悎璁?鏀惰垂-閫€璐瑰噣棰?',
  MODIFY COLUMN cash_total DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鐜伴噾鍚堣',
  MODIFY COLUMN free_total DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍑忓厤鍚堣(鏀惰垂-閫€璐瑰噣棰?',
  MODIFY COLUMN fund_total DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍩洪噾鍚堣',
  MODIFY COLUMN refund_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '閫€璐归噾棰?',
  MODIFY COLUMN reg_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎸傚彿璐瑰噣棰?鎸傚彿-閫€鍙?',
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎬婚噾棰?',
  MODIFY COLUMN wechat_total DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '寰俊鍚堣(鏀惰垂-閫€璐瑰噣棰?';
ALTER TABLE his_discharge_pickup
  MODIFY COLUMN qty DECIMAL(16,4) NULL DEFAULT 0.0000 COMMENT '甯﹁嵂閲?鏈€灏忓崟浣?';
ALTER TABLE his_dispense
  MODIFY COLUMN price_diff DECIMAL(16,2) NULL DEFAULT NULL COMMENT '浠峰樊=瀹炲彂-璁¤垂(涓嶅悜鎮ｈ€呰ˉ閫€, 浠呭璐?',
  MODIFY COLUMN stock_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '瀹炲彂鎵规闆跺敭閲戦(鍙戣嵂鏃舵寜鍑哄簱鎵规浠锋眹鎬? 闄㈠唴瀵硅处)',
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎬婚噾棰?';
ALTER TABLE his_drug_catalog
  MODIFY COLUMN unit_dose DECIMAL(16,4) NULL DEFAULT NULL COMMENT '姣忔渶灏忓寘瑁呭崟浣嶅惈鑽噺(濡?.25g/绮?';
ALTER TABLE his_drug_maintenance_item
  MODIFY COLUMN qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '鍦ㄥ簱鏁伴噺';
ALTER TABLE his_drug_price_adjust
  MODIFY COLUMN total_diff_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍦ㄥ簱閲戦褰卞搷鍚堣';
ALTER TABLE his_drug_price_adjust_item
  MODIFY COLUMN impact_stock_qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '褰撳墠鍦ㄥ簱鏁伴噺(棰勮褰卞搷)',
  MODIFY COLUMN new_purchase DECIMAL(16,6) NULL DEFAULT NULL COMMENT '鏂拌繘浠?',
  MODIFY COLUMN new_retail DECIMAL(16,6) NULL DEFAULT NULL COMMENT '鏂伴浂鍞环',
  MODIFY COLUMN old_purchase DECIMAL(16,6) NULL DEFAULT NULL COMMENT '鍘熻繘浠?',
  MODIFY COLUMN old_retail DECIMAL(16,6) NULL DEFAULT NULL COMMENT '鍘熼浂鍞环';
ALTER TABLE his_drug_return
  MODIFY COLUMN return_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '閫€鑽噾棰?';
ALTER TABLE his_drug_return_item
  MODIFY COLUMN return_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鏈璇ヨ閫€鑽噾棰?鎸夊垝浠峰師浠?';
ALTER TABLE his_drug_stock
  MODIFY COLUMN cost_price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '杩涗环',
  MODIFY COLUMN qty DECIMAL(16,4) NOT NULL DEFAULT 0.00 COMMENT '搴撳瓨鏁伴噺',
  MODIFY COLUMN warn_qty DECIMAL(16,4) NULL DEFAULT 10.00 COMMENT '棰勮閲?';
ALTER TABLE his_drug_trace_code
  MODIFY COLUMN min_pack_qty DECIMAL(16,4) NULL DEFAULT 1.00 COMMENT '鏈€灏忓寘瑁呮暟閲?';
ALTER TABLE his_fee_type_dict
  MODIFY COLUMN ctl_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '闂ㄨ瘖娆″潎闄愰(鍏?',
  MODIFY COLUMN ctl_day_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '浣忛櫌鏃ュ潎闄愰(鍏?',
  MODIFY COLUMN ctl_ipt_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '浣忛櫌娆″潎闄愰(鍏?',
  MODIFY COLUMN discount_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '鍥哄畾鍑忓厤閲戦(discount_mode=AMOUNT 鏃剁敓鏁?';
ALTER TABLE his_green_channel_credit
  MODIFY COLUMN credit_limit DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '淇＄敤棰濆害(鍏?',
  MODIFY COLUMN used_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '宸蹭娇鐢ㄩ搴?鍏?';
ALTER TABLE his_inp_daily_bill
  MODIFY COLUMN cumulative_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '鍦ㄩ櫌绱璐圭敤',
  MODIFY COLUMN deposit_balance DECIMAL(16,2) NULL DEFAULT NULL COMMENT '棰勪氦閲戜綑棰?',
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '褰撴棩璐圭敤鍚堣';
ALTER TABLE his_inp_deposit
  MODIFY COLUMN amount DECIMAL(16,2) NOT NULL COMMENT '閲戦',
  MODIFY COLUMN balance_after DECIMAL(16,2) NULL DEFAULT NULL COMMENT '鎿嶄綔鍚庝綑棰?';
ALTER TABLE his_inp_dispense
  MODIFY COLUMN actual_qty DECIMAL(16,4) NULL DEFAULT 0.0000 COMMENT '瀹炲彂閲?鍙栨暣鍚?鍐叉姷, 鏈€灏忓崟浣?',
  MODIFY COLUMN offset_qty DECIMAL(16,4) NULL DEFAULT 0.0000 COMMENT '鍐叉姷閲?鐥呭尯鏆傚瓨鎶垫墸搴斿彂)',
  MODIFY COLUMN over_qty DECIMAL(16,4) NULL DEFAULT 0.0000 COMMENT '澶氬彂閲?鏁村寘瑁呭彇鏁存孩鍑洪儴鍒?',
  MODIFY COLUMN return_qty DECIMAL(16,4) NULL DEFAULT 0.0000 COMMENT '绱閫€鍥?鏆傚瓨閲?',
  MODIFY COLUMN should_qty DECIMAL(16,4) NULL DEFAULT 0.0000 COMMENT '搴斿彂閲?鍖诲槺閲? 鏈€灏忓崟浣?';
ALTER TABLE his_inp_fee_alert
  MODIFY COLUMN alert_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '棰勮鏃堕噾棰?',
  MODIFY COLUMN threshold_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '闃堝€奸噾棰?';
ALTER TABLE his_inp_settle
  MODIFY COLUMN acct_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '涓处鏀粯',
  MODIFY COLUMN cash_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鐜伴噾鏀粯',
  MODIFY COLUMN deposit_deduct DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '棰勪氦閲戞姷鎵?',
  MODIFY COLUMN fund_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍩洪噾鏀粯',
  MODIFY COLUMN refund_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '閫€杩橀噾棰?',
  MODIFY COLUMN self_pay DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鑷粯閲戦',
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '鎬婚噾棰?';
ALTER TABLE his_inp_visit
  MODIFY COLUMN deposit_balance DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '棰勪氦閲戜綑棰?',
  MODIFY COLUMN deposit_warning_amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '棰勪氦閲戦璀︾嚎',
  MODIFY COLUMN total_cost DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎬昏垂鐢?';
ALTER TABLE his_invoice
  MODIFY COLUMN amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '寮€绁ㄩ噾棰?';
ALTER TABLE his_med_dict
  MODIFY COLUMN daily_times DECIMAL(16,4) NULL DEFAULT NULL COMMENT '姣忔棩娆℃暟(浠呴娆? 椹卞姩鍙戣嵂閲忔崲绠? 鏀寔灏忔暟濡?.5=闅旀棩)';
ALTER TABLE his_mr_workload
  MODIFY COLUMN amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '閲戦(鍙┖)',
  MODIFY COLUMN qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '鏁伴噺';
ALTER TABLE his_order
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍗曟嵁閲戦';
ALTER TABLE his_pathway_template
  MODIFY COLUMN total_cost DECIMAL(16,2) NULL DEFAULT NULL COMMENT '棰勪及鎬昏垂鐢?';
ALTER TABLE his_payment_detail
  MODIFY COLUMN amount DECIMAL(16,2) NOT NULL COMMENT '鏀粯閲戦';
ALTER TABLE his_prescription_item
  MODIFY COLUMN unit_dose DECIMAL(16,4) NULL DEFAULT NULL COMMENT '姣忔渶灏忓寘瑁呭崟浣嶅惈鑽噺(鎹㈢畻蹇収)';
ALTER TABLE his_purchase_order
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '璁㈠崟閲戦鍚堣';
ALTER TABLE his_purchase_order_item
  MODIFY COLUMN amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '閲戦',
  MODIFY COLUMN price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '杩涗环',
  MODIFY COLUMN qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '璁㈣喘鏁伴噺',
  MODIFY COLUMN qty_received DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '宸插埌璐у叆搴撴暟閲?';
ALTER TABLE his_purchase_plan
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '璁″垝閲戦鍚堣';
ALTER TABLE his_purchase_plan_item
  MODIFY COLUMN amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '棰勪及閲戦',
  MODIFY COLUMN cur_stock DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '褰撳墠搴撳瓨(蹇収)',
  MODIFY COLUMN dispense_qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '鑽埧鍙戣嵂閲?蹇収)',
  MODIFY COLUMN hi_qty DECIMAL(16,4) NULL DEFAULT NULL COMMENT '楂樺偍鏍囧噯(蹇収)',
  MODIFY COLUMN last_month_in DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '涓婃湀鍏ュ簱閲?蹇収)',
  MODIFY COLUMN last_month_out DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '涓婃湀鍑哄簱閲?蹇収)',
  MODIFY COLUMN lo_qty DECIMAL(16,4) NULL DEFAULT NULL COMMENT '浣庡偍鏍囧噯(蹇収)',
  MODIFY COLUMN price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '棰勪及杩涗环',
  MODIFY COLUMN qty_suggest DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '寤鸿閲囪喘鏁伴噺';
ALTER TABLE his_purchase_rule
  MODIFY COLUMN hi_qty DECIMAL(16,4) NULL DEFAULT NULL COMMENT '楂樺偍鏍囧噯',
  MODIFY COLUMN lo_qty DECIMAL(16,4) NULL DEFAULT NULL COMMENT '浣庡偍鏍囧噯(琛ヨ揣鐐?';
ALTER TABLE his_reg_payment
  MODIFY COLUMN amount DECIMAL(16,2) NOT NULL DEFAULT 0.00 COMMENT '閲戦(姝ｆ暟, 鏂瑰悜鐢眃irection琛ㄨ揪)';
ALTER TABLE his_registration
  MODIFY COLUMN actual_fee DECIMAL(16,2) NULL DEFAULT NULL COMMENT '瀹炴敹閲戦(鎸傚彿璐?鍑忓厤閲戦)',
  MODIFY COLUMN discount_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍑忓厤閲戦',
  MODIFY COLUMN reg_fee DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎸傚彿璐?';
ALTER TABLE his_schedule
  MODIFY COLUMN reg_fee DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎸傚彿璐?';
ALTER TABLE his_schedule_template
  MODIFY COLUMN reg_fee DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎸傚彿璐?';
ALTER TABLE his_staff
  MODIFY COLUMN reg_fee DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '榛樿鎸傚彿璐?璇婃煡璐?';
ALTER TABLE his_stock_accept
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '楠屾敹閲戦鍚堣';
ALTER TABLE his_stock_accept_item
  MODIFY COLUMN amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '閲戦',
  MODIFY COLUMN cost_price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '杩涗环',
  MODIFY COLUMN qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '楠屾敹鏁伴噺';
ALTER TABLE his_stock_balance
  MODIFY COLUMN actual_in_price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '瀹為檯鍑哄簱缁撹浆杩涗环',
  MODIFY COLUMN diff_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '杩涗环宸?锛堝疄闄?鍘燂級*鏁伴噺',
  MODIFY COLUMN orig_in_price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '鍘熸寕璐﹁繘浠?',
  MODIFY COLUMN qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '鍐叉姷鏁伴噺';
ALTER TABLE his_stock_check
  MODIFY COLUMN loss_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鐩樹簭閲戦鍚堣',
  MODIFY COLUMN profit_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鐩樼泩閲戦鍚堣';
ALTER TABLE his_stock_check_item
  MODIFY COLUMN actual_qty DECIMAL(16,4) NULL DEFAULT NULL COMMENT '瀹炵洏鏁伴噺',
  MODIFY COLUMN cost_price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '杩涗环(蹇収)',
  MODIFY COLUMN diff_qty DECIMAL(16,4) NULL DEFAULT NULL COMMENT '宸紓鏁伴噺(瀹炵洏-璐﹂潰; 姝?鐩樼泩 璐?鐩樹簭)',
  MODIFY COLUMN system_qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '绯荤粺璐﹂潰鏁伴噺';
ALTER TABLE his_stock_in
  MODIFY COLUMN paid_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '宸蹭粯閲戦(渚涘簲鍟嗕粯娆惧洖鍐?',
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎬婚噾棰?';
ALTER TABLE his_stock_in_item
  MODIFY COLUMN amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '灏忚閲戦',
  MODIFY COLUMN cost_price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '杩涗环',
  MODIFY COLUMN min_qty DECIMAL(16,4) NULL DEFAULT NULL COMMENT '鏈€灏忓崟浣嶉噺=澶у寘瑁呮暟*鍖呰姣?',
  MODIFY COLUMN pack_qty DECIMAL(16,4) NULL DEFAULT NULL COMMENT '澶у寘瑁呮暟(澶氬崟浣嶅綍鍏?',
  MODIFY COLUMN purchase_price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '鎸傝处杩涗环(寰呮牳)',
  MODIFY COLUMN qty DECIMAL(16,4) NOT NULL COMMENT '鏁伴噺';
ALTER TABLE his_stock_month_end
  MODIFY COLUMN closing_qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '鏈熸湯鏁伴噺(瀹炵墿璐?',
  MODIFY COLUMN in_qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '鏈湡鍏ュ簱鏁伴噺',
  MODIFY COLUMN opening_qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '鏈熷垵鏁伴噺(瀹炵墿璐?',
  MODIFY COLUMN out_qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '鏈湡鍑哄簱鏁伴噺';
ALTER TABLE his_stock_out
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鎬婚噾棰?';
ALTER TABLE his_stock_out_item
  MODIFY COLUMN amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '灏忚閲戦',
  MODIFY COLUMN cost_price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '杩涗环',
  MODIFY COLUMN qty DECIMAL(16,4) NOT NULL COMMENT '鏁伴噺';
ALTER TABLE his_supplier_payment
  MODIFY COLUMN amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鏈浠樻鎬婚';
ALTER TABLE his_supplier_payment_item
  MODIFY COLUMN in_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鍏ュ簱搴斾粯棰?蹇収)',
  MODIFY COLUMN paid_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '鏈鍒嗘憡浠樻棰?',
  MODIFY COLUMN paid_before DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '缁撶畻鍓嶅凡浠橀(蹇収)';
ALTER TABLE his_transfer
  MODIFY COLUMN total_amount DECIMAL(16,2) NULL DEFAULT 0.00 COMMENT '璋冩嫧閲戦鍚堣';
ALTER TABLE his_transfer_item
  MODIFY COLUMN amount DECIMAL(16,2) NULL DEFAULT NULL COMMENT '灏忚閲戦',
  MODIFY COLUMN cost_price DECIMAL(16,6) NULL DEFAULT NULL COMMENT '杩涗环(蹇収)',
  MODIFY COLUMN qty DECIMAL(16,4) NULL DEFAULT 0.00 COMMENT '璋冩嫧鏁伴噺';
ALTER TABLE his_ward_staging
  MODIFY COLUMN staged_qty DECIMAL(16,4) NULL DEFAULT 0.0000 COMMENT '鏆傚瓨閲?鏈€€鍥炲彲鍐叉姷)',
  MODIFY COLUMN used_qty DECIMAL(16,4) NULL DEFAULT 0.0000 COMMENT '宸插啿鎶甸噺';
