package com.yb.hi.service.inpatient;

import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.yb.hi.dto.inpatient.NursingClinicalEventDTO;
import com.yb.hi.entity.inpatient.HisInpVisit;
import com.yb.hi.entity.inpatient.HisNursingClinicalEvent;
import com.yb.hi.framework.common.BizException;
import com.yb.hi.framework.common.Roles;
import com.yb.hi.framework.tenant.LoginUser;
import com.yb.hi.framework.tenant.UserContext;
import com.yb.hi.mapper.inpatient.HisInpVisitMapper;
import com.yb.hi.mapper.inpatient.HisNursingClinicalEventMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * 护理临床事件服务(P4c): 入科/出科/死亡/手术/转入/转出/分娩/抢救事件时间轴。
 * 说明:
 * 1) 表 his_nursing_clinical_event 由 DictSchemaMigration@0 幂等建出, 走 MyBatis-Plus 正常租户隔离;
 * 2) 双通道登记: 手动登记(auto_generated=0, source_type=manual)与自动触发(auto_generated=1,
 *    source_type=order/visit_status); autoRecord 供就诊状态/医嘱执行侧服务在状态变更处直接调用,
 *    推送失败静默(仅告警日志), 不影响主流程事务;
 * 3) event_type 限固定枚举集: admission/discharge/death/surgery/transfer_in/transfer_out/
 *    delivery/resuscitation;
 * 4) 写操作校验就诊/记录归属机构与当前登录机构一致(平台超管放行), 沿用住院护士站口径;
 *    autoRecord 免登录上下文校验(服务端内部触发场景)。
 */
@Slf4j
@Service
public class NursingClinicalEventService {

    /** 登记来源: 0手动 1自动生成 */
    public static final int SOURCE_MANUAL = 0;
    public static final int SOURCE_AUTO = 1;

    /** 事件类型固定集(与 his_nursing_clinical_event.event_type 注释口径一致) */
    public static final Set<String> EVENT_TYPES = new HashSet<>(Arrays.asList(
            "admission", "discharge", "death", "surgery", "transfer_in", "transfer_out",
            "delivery", "resuscitation"));

    private final HisNursingClinicalEventMapper eventMapper;
    private final HisInpVisitMapper visitMapper;

    public NursingClinicalEventService(HisNursingClinicalEventMapper eventMapper,
                                       HisInpVisitMapper visitMapper) {
        this.eventMapper = eventMapper;
        this.visitMapper = visitMapper;
    }

    /* ================= 手动登记 ================= */

    /** 手动登记事件: 校验就诊归属与字段合法性 → 落库(auto_generated=0, source_type 缺省 manual)。 */
    @Transactional(rollbackFor = Exception.class)
    public HisNursingClinicalEvent record(NursingClinicalEventDTO dto) {
        if (dto == null) {
            throw new BizException(400, "请求体不能为空");
        }
        if (dto.getInpVisitId() == null) {
            throw new BizException(400, "住院就诊ID不能为空");
        }
        if (!StringUtils.hasText(dto.getEventType())) {
            throw new BizException(400, "事件类型不能为空");
        }
        String eventType = dto.getEventType().trim();
        if (!EVENT_TYPES.contains(eventType)) {
            throw new BizException(400, "事件类型无效: " + dto.getEventType()
                    + "(有效值: admission/discharge/death/surgery/transfer_in/transfer_out/delivery/resuscitation)");
        }
        if (StringUtils.hasText(dto.getEventDesc()) && dto.getEventDesc().trim().length() > 500) {
            throw new BizException(400, "事件描述不能超过500字");
        }

        HisInpVisit visit = requireVisit(dto.getInpVisitId());
        Long patientId = dto.getPatientId() != null ? dto.getPatientId() : visit.getPatientId();
        if (patientId == null) {
            throw new BizException(400, "就诊记录缺少患者信息, 无法登记事件");
        }

        HisNursingClinicalEvent e = new HisNursingClinicalEvent();
        e.setOrgId(visit.getOrgId());
        e.setInpVisitId(visit.getId());
        e.setPatientId(patientId);
        e.setEventType(eventType);
        e.setEventTime(dto.getEventTime() != null ? dto.getEventTime() : LocalDateTime.now());
        e.setEventDesc(trimToNull(dto.getEventDesc()));
        e.setAutoGenerated(SOURCE_MANUAL);
        e.setSourceType(StringUtils.hasText(dto.getSourceType()) ? dto.getSourceType().trim() : "manual");
        e.setSourceId(dto.getSourceId());
        eventMapper.insert(e);
        return e;
    }

    /* ================= 自动触发 ================= */

    /**
     * 自动登记事件(供就诊状态/医嘱执行侧服务在状态变更处调用):
     * auto_generated=1, source_type=order/visit_status, 事件时间取状态变更时间(缺省当前)。
     * 说明: 事件落库失败仅告警日志, 不向调用方抛异常(自动通道不得阻断主业务事务)。
     */
    public void autoRecord(Long inpVisitId, Long patientId, String eventType, LocalDateTime eventTime,
                           String sourceType, Long sourceId) {
        try {
            if (inpVisitId == null || !StringUtils.hasText(eventType)) {
                log.warn("临床事件自动登记参数缺失, 跳过: inpVisitId={}, eventType={}", inpVisitId, eventType);
                return;
            }
            if (!EVENT_TYPES.contains(eventType.trim())) {
                log.warn("临床事件自动登记类型无效, 跳过: eventType={}", eventType);
                return;
            }
            HisInpVisit visit = visitMapper.selectById(inpVisitId);
            if (visit == null) {
                log.warn("临床事件自动登记就诊不存在, 跳过: inpVisitId={}", inpVisitId);
                return;
            }
            Long pid = patientId != null ? patientId : visit.getPatientId();
            HisNursingClinicalEvent e = new HisNursingClinicalEvent();
            e.setOrgId(visit.getOrgId());
            e.setInpVisitId(visit.getId());
            e.setPatientId(pid);
            e.setEventType(eventType.trim());
            e.setEventTime(eventTime != null ? eventTime : LocalDateTime.now());
            e.setEventDesc(null);
            e.setAutoGenerated(SOURCE_AUTO);
            e.setSourceType(StringUtils.hasText(sourceType) ? sourceType.trim() : "visit_status");
            e.setSourceId(sourceId);
            eventMapper.insert(e);
            log.info("临床事件自动登记: visitId={}, type={}, source={}/{}, eventTime={}",
                    inpVisitId, eventType, e.getSourceType(), sourceId, e.getEventTime());
        } catch (Exception ex) {
            log.warn("临床事件自动登记失败(不影响主流程): visitId={}, type={}, 原因={}",
                    inpVisitId, eventType, ex.getMessage());
        }
    }

    /* ================= 查询 ================= */

    /** 事件时间轴(按就诊): 按事件时间升序(时间轴自然序), 同刻按 ID 升序保证稳定。 */
    public List<HisNursingClinicalEvent> listByVisit(Long inpVisitId) {
        requireVisit(inpVisitId);
        return eventMapper.selectList(Wrappers.<HisNursingClinicalEvent>lambdaQuery()
                .eq(HisNursingClinicalEvent::getInpVisitId, inpVisitId)
                .orderByAsc(HisNursingClinicalEvent::getEventTime)
                .orderByAsc(HisNursingClinicalEvent::getId));
    }

    /** 事件时间轴(按就诊+时段, 临时体温单/交班报告数据源): 事件时间闭区间, 升序。 */
    public List<HisNursingClinicalEvent> listByVisitAndRange(Long inpVisitId, LocalDateTime start,
                                                             LocalDateTime end) {
        requireVisit(inpVisitId);
        if (start != null && end != null && start.isAfter(end)) {
            throw new BizException(400, "开始时间不能晚于结束时间");
        }
        return eventMapper.selectList(Wrappers.<HisNursingClinicalEvent>lambdaQuery()
                .eq(HisNursingClinicalEvent::getInpVisitId, inpVisitId)
                .ge(start != null, HisNursingClinicalEvent::getEventTime, start)
                .le(end != null, HisNursingClinicalEvent::getEventTime, end)
                .orderByAsc(HisNursingClinicalEvent::getEventTime)
                .orderByAsc(HisNursingClinicalEvent::getId));
    }

    /* ================= 校验 / 内部工具 ================= */

    /** 就诊必读校验: 存在 + 归属当前登录机构(平台超管放行), 沿用住院护士站口径。 */
    private HisInpVisit requireVisit(Long visitId) {
        if (visitId == null) {
            throw new BizException(400, "住院就诊ID不能为空");
        }
        HisInpVisit visit = visitMapper.selectById(visitId);
        if (visit == null) {
            throw new BizException(404, "住院就诊记录不存在");
        }
        LoginUser u = UserContext.get();
        if (u == null) {
            throw new BizException(401, "未登录");
        }
        if (!u.hasRole(Roles.SUPER_ADMIN) && visit.getOrgId() != null && u.getOrgId() != null
                && !visit.getOrgId().equals(u.getOrgId())) {
            throw new BizException(403, "该就诊不属于当前登录机构, 无权操作");
        }
        return visit;
    }

    private static String trimToNull(String s) {
        return StringUtils.hasText(s) ? s.trim() : null;
    }
}
